version: "3.9"
services:
  backend:
    build: ./backend
    container_name: blackjack-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: blackjack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
